name       : qwt
version    : 6.1.4
release    : 4
source     :
    - https://netix.dl.sourceforge.net/project/qwt/qwt/6.1.4/qwt-6.1.4.tar.bz2 : 1529215329e51fc562e0009505a838f427919a18b362afff441f035b2d9b5bd9
license    : LGPL-2.1-or-later
component  : programming
summary    : Qwt is an extension to the libraries of the Qt Project
description: |
    The Qwt library contains widgets and components which are primarily useful for technical and scientifical purposes.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Svg)
setup      : |
    %patch -p1 < $pkgfiles/qwtconfig.patch
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    mv $installdir/usr/share/doc/qwt/man $installdir/usr/share/man
