name       : qwt
version    : 6.1.3
release    : 1
source     :
    - http://netix.dl.sourceforge.net/project/qwt/qwt/6.1.3/qwt-6.1.3.tar.bz2 : f3ecd34e72a9a2b08422fb6c8e909ca76f4ce5fa77acad7a2883b701f4309733
license    : LGPL-2.1
component  : programming
summary    : Qwt is an extension to the libraries of the Qt Project.
description: |
    The Qwt library contains widgets and components which are primarily useful for technical and scientifical purposes.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(QtCore)
setup      : |
    %patch -p1 < $pkgfiles/qwtconfig.patch
    qmake-qt4 PREFIX=$installdir qwt.pro \
              QMAKE_MOC=/usr/bin/moc-qt4 \
              QMAKE_RCC=/usr/bin/rcc-qt4 \
              QMAKE_UIC=/usr/bin/uic-qt4
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/doc/qwt/man $installdir/usr/share/man